//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnia.Client.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attributes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attributes()
        {
            this.Relationships = new HashSet<Relationships>();
            this.Relationships1 = new HashSet<Relationships>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CollectionId { get; set; }
        public bool IsNullable { get; set; }
        public bool IsPrimaryKey { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Precision { get; set; }
        public Nullable<int> Scale { get; set; }
        public int Type { get; set; }
        public string DefaultValue { get; set; }
        public string Formula { get; set; }
        public bool IsPersistent { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Increment { get; set; }
        public Nullable<decimal> Seed { get; set; }
        public bool IsSparse { get; set; }
    
        public virtual Collections Collections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationships> Relationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationships> Relationships1 { get; set; }
    }
}
