//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnia.Client.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationships
    {
        public int Id { get; set; }
        public int AttributeId { get; set; }
        public int RelatedAttributeId { get; set; }
    
        public virtual Attributes Attributes { get; set; }
        public virtual Attributes Attributes1 { get; set; }
    }
}
