//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnia.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationOAuthProviders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationOAuthProviders()
        {
            this.UserOAuthProviderLogins = new HashSet<UserOAuthProviderLogins>();
        }
    
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public int OAuthProviderId { get; set; }
        public string ExternalId { get; set; }
        public string ExternalSecret { get; set; }
        public string Scope { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual OAuthProviders OAuthProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOAuthProviderLogins> UserOAuthProviderLogins { get; set; }
    }
}
