//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnia.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDatabases
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public int SqlInstanceId { get; set; }
        public string DatabaseName { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual SqlInstances SqlInstances { get; set; }
    }
}
