//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnia.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OmniaEntities : DbContext
    {
        public OmniaEntities()
            : base("name=OmniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationOAuthProviders> ApplicationOAuthProviders { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<OAuthProviders> OAuthProviders { get; set; }
        public virtual DbSet<UserOAuthProviderLogins> UserOAuthProviderLogins { get; set; }
        public virtual DbSet<UserOAuthProviders> UserOAuthProviders { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ApplicationDatabases> ApplicationDatabases { get; set; }
        public virtual DbSet<SqlInstances> SqlInstances { get; set; }
    
        public virtual ObjectResult<GetAccessTokenUser_Result> GetAccessTokenUser(string accessToken, ObjectParameter applicationId)
        {
            var accessTokenParameter = accessToken != null ?
                new ObjectParameter("accessToken", accessToken) :
                new ObjectParameter("accessToken", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAccessTokenUser_Result>("GetAccessTokenUser", accessTokenParameter, applicationId);
        }
    }
}
