//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnia.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOAuthProviders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserOAuthProviders()
        {
            this.UserOAuthProviderLogins = new HashSet<UserOAuthProviderLogins>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int OAuthProviderId { get; set; }
        public string ExternalId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PictureUri { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual OAuthProviders OAuthProviders { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOAuthProviderLogins> UserOAuthProviderLogins { get; set; }
    }
}
